
# Axolotl Configuration for Bilingual Judgmental Dataset Training
# This config is optimized for training AAOIFI Shari'ah Standards verification models

base_model: microsoft/DialoGPT-medium
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Quantization settings
load_in_8bit: false
load_in_4bit: true
strict: false

# Dataset configuration
datasets:
  - path: data/train.jsonl
    type: alpaca

# Validation dataset
val_set_size: 0.0
eval_dataset:
  - path: data/val.jsonl
    type: alpaca

# Data preparation
dataset_prepared_path: prepared_data/judgmental
output_dir: outputs/judgmental_model
sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true

# LoRA adapter configuration
adapter: lora
lora_model_dir: ""
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj

# Training parameters
gradient_accumulation_steps: 8
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 1e-5

# Training configuration
train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: false

# Memory optimization
gradient_checkpointing: true
early_stopping_patience: ""
resume_from_checkpoint: ""
local_rank: ""

# Logging and evaluation
logging_steps: 10
xformers_attention: ""
flash_attention: true
warmup_steps: 100
evals_per_epoch: 2
save_steps: ""
eval_steps: 100
save_total_limit: 3

# Special tokens
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
  pad_token: "[PAD]"

# Weights & Biases (optional)
wandb_project: "judgmental_bilingual"
wandb_entity: ""
wandb_watch: ""
wandb_name: ""
wandb_log_model: ""
